# Simple workflow for deploying static content to GitHub Pages
  # 允许您从操作选项卡手动运行此工作流程: Deploy static content to Pages

on:
  # 在针对默认分支的推送触发# Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # 允许您从操作选项卡手动运行此工作流程# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  内容：阅读: read
  页数：写: write
  id-token: 写: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 单独部署作业，因为我们只是进行部署# Single deploy job since we're just deploying
  deploy:
    environment:
      名称: github-pages: github-pages
      url: ${{ steps.deployment.outputs.page_url }}: ${{ steps.deployment.outputs.page_url }}
    运行于: ubuntu-latest: ubuntu-latest
    steps:
      - 名称: 结账name: Checkout
        用途：actions/checkout@v4: actions/checkout@v4
      - 名称: 设置页面name: Setup Pages
        用途：actions/configure-pages@v5: actions/configure-pages@v5
      - 名称：上传工件name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
